from typing import Literal

from pydantic import BaseModel, Field


Impact = Literal["positive", "negative", "neutral"]


class MetricChange(BaseModel):
    """
    Represents how an individual assessment metric changed between
    the original and simulated assessment.
    """

    component: str
    metric: str

    # Business metric values
    before_value: float
    after_value: float
    value_change: float

    # Assessment impact
    before_score: float
    after_score: float
    score_change: float

    # Overall impact on assessment
    impact: Impact


class TopImpactDriver(BaseModel):
    """
    Represents the metrics that contributed the most to the
    assessment change.
    """

    component: str
    metric: str

    before_score: float
    after_score: float
    score_change: float

    impact: Impact


class SimulationInsight(BaseModel):
    """
    Human-readable explanation of the simulation result.
    Initially rule-based, later generated using an LLM.
    """

    headline: str

    summary: str

    business_impact: str

    recommendation: str


class Simulation(BaseModel):
    """
    Scenario analysis output generated by comparing two assessments.
    """

    metric_changes: list[MetricChange] = Field(default_factory=list)

    top_impact_drivers: list[TopImpactDriver] = Field(default_factory=list)

    insight: SimulationInsight | None = None